### ISSUE TITLE
Everything looks black

### ISSUE THREAD

**Issue by NicolasPL64** [MorsGames/sm64plus#10]
![image](https://user-images.githubusercontent.com/31411531/114591911-fe6f7980-9c4f-11eb-85f0-d130e1dd801d.png)

**Comment by NicolasPL64** [comment]
![image](https://user-images.githubusercontent.com/31411531/114592396-80f83900-9c50-11eb-85ae-d6a55ccd6305.png)

**Comment by RGG200** [comment]
May be your rom IS Corrupted because i had thé same issue with net64+ and i just took again my cardrige to get à New rom then i converted it to.z64 and it worked (note i tryed it in net 64+ i think this can help you because i had thé same with my emulator when i was playing net64+)
Hope this can help you!

**Comment by MorsGames** [comment]
That's a known issue and is addressed in the FAQ for now, I'm currently working on a permanent fix.
