### ISSUE TITLE
Use dumped EEPROM save from original cartridge

### ISSUE THREAD

**Issue by parski** [MorsGames/sm64plus#14]
I've dumped my Super Mario 64 cartridge to get the ROM to use for compiling an executable. While I was at it I also dumped the EEPROM to get my save data. Now I want to look into getting my cartridge save data to work with this PC port but I can't even seem to find the save file. Want to point me in the right direction? Has anyone managed to get original save data to work with a PC version?

**Comment by parski** [comment]
For anyone else looking for the save on Windows it's in:
```
C:\Users\user\AppData\Local\SM64Plus
```

The filename is: `savedata.bin`.

**Comment by parski** [comment]
Byte and word swapping seems to almost do the trick comparing a just created save (top) with my original save (bottom).

![save](https://user-images.githubusercontent.com/2445818/115023410-0da82e80-9ebf-11eb-8940-13f078799bdf.png)

Wondering if it's either that the PC version adds other stuff to the save data or if it might be a regional thing since my cartridge is PAL.

**Comment by MorsGames** [comment]
It's because I believe the emulators use little endian while the port uses big endian for the save files, it could be other way around though. I might add a toggle for that as a setting to the next version.

The port does add new stuff though, but it should be compatible with the N64 version regardless.

**Comment by parski** [comment]
Ah, so you're reading the save files like an emulator? Why?

Anyway, previously I byte- and word swapped the save file but this had the same result in game as using the EEPROM dump straight up. Every save file would be listed as "NEW" and selecting it would start the intro cinematic.

However, if I only word swap (no byte swap) the top two slots are listed as "NEW" permadeath slots even though I have not enabled permadeath obviously since the save file is a dump from a PAL launch copy of Super Mario 64.

![slot](https://user-images.githubusercontent.com/2445818/115383871-9fbd7900-a1d6-11eb-8280-4b2dd62f51f7.PNG)

Selecting the top leftmost slot does not lead to the intro cinematic but puts me at the spawn point with my stars but Mario has no had and he's banting as if he has low HP.

![start](https://user-images.githubusercontent.com/2445818/115383969-c085ce80-a1d6-11eb-83ef-8de155d66e44.PNG)

Lakitu is at the bridge and some doors have been locked again. Progress seems pretty garbled in general.

![sm64](https://user-images.githubusercontent.com/2445818/115382842-6e907900-a1d5-11eb-8729-3f59cd5f662f.PNG)

Are you sure the added things would be compatible with the Nintendo 64 version because it doesn't seem like it the other way around.

**Comment by MorsGames** [comment]
> Ah, so you're reading the save files like an emulator? Why?
Well, I think that's just how the game works, the way save files work is pretty much the same as the base port I based my fork on.

I looked a bit more into this issue and apparently I was wrong about the whole byte order thing. I THINK the save files for the original are in big-endian since that's the native order of N64's CPU, meanwhile the port uses little-endian since that's the default for x86 platforms.

And I know that the save files should be interchangeable in theory since I use empty bytes for all the extra save options. I did a very similar thing back then when this was a ROM hack and not a fork of the PC port and I could just swap the save files and it would just work.

I'll try artificially swapping the bytes myself to see what happens, but unfortunately this is a topic I'm not super familiar with, and I don't want to spend hours on this feature specifically, so if I can't get it working like that I'll probably scrap the idea for that save file toggle.

**Comment by parski** [comment]
That makes sense that the save files use the endianness of the host architecture.

> And I know that the save files should be interchangeable in theory since I use empty bytes for all the extra save options.

And those bytes are at an address at the end of the save data? As in appended to the regular data. If they are in the beginning maybe my data is offset or something. Just a guess.

> I don't want to spend hours on this feature specifically

I hope I didn't make you feel like you have to spend time on this. I created the issue to show my intent but also to see if anybody had done it successfully before and could help me or at least to document my process of figuring out how to get this to work. I'm very thankful for the help you're providing but feel to close the issue and refer me to my chambers if you feel it is out of place.

**Comment by parski** [comment]
Here is my EEPROM dump in case anybody wants a dump to play with:

[SUPERMARIO64.zip](https://github.com/MorsGames/sm64plus/files/6350353/SUPERMARIO64.zip)

**Comment by MorsGames** [comment]
> I hope I didn't make you feel like you have to spend time on this. I created the issue to show my intent but also to see if anybody had done it successfully before and could help me or at least to document my process of figuring out how to get this to work. I'm very thankful for the help you're providing but feel to close the issue and refer me to my chambers if you feel it is out of place.
Nah it's fine, it's something I wanted to add in myself after seeing this issue.

**Comment by MorsGames** [comment]
I messed around for a bit longer and couldn't really figure it out. I'm sure it would be possible but I'm really not sure how exactly, so I'm closing this issue (at least for now).
