### ISSUE TITLE
The save deleted itself

### ISSUE THREAD

**Issue by NuclearThief** [MorsGames/sm64plus#15]
Hi, i was playing SM64Plus (obviously) and i yesterday i 100% the game, turned off the game by pausing and then pressing Z & R. Today i wanted to just jump around aaaaand the save was gone. It will be good when it'll be fixed, and could i get a 100% save file to download? Beacuse i don't want to do this again, it took me long long time

**Comment by MorsGames** [comment]
I believe you can find a full save file from Google, save files for other PC port forks should work here as well.

I highly doubt that the game deleted your save file though, there isn't really any code to actually do that. Corruption could be possible, but that's essentially impossible for me to fix since it would be a random one-off occurrence.

**Comment by NuclearThief** [comment]
Oh, ok
