### ISSUE TITLE
Poles in Dire Dire Docks don't spawn even after the first star.

### ISSUE THREAD

**Issue by AleNinten** [MorsGames/sm64plus#30]
When the first star is completed, the submarine should go away and the poles to grab the red coins should spawn in for the later stars. However, no mater with my settings or the vanilla ones, the sub always stay, preventing the poles from spawining, thus making the red coin star incredibly difficult, or even almost impossible to obtain.

**Comment by MorsGames** [comment]
This is how it is in the base game too, you have to finish fire sea first to get the poles to appear. It's not tied to the mission number.

I will add an option to tie it to the mission number since many people seem to get confused about it and think it's a bug, but it's not very high priority at the moment.

**Comment by AleNinten** [comment]
Oh man, this being a childhood game and not remembering that is very embarrasing... thanks for reminding me Mors. Keep the amazing work! This is a very outstanding builld for sure.
