### ISSUE TITLE
"Stay in Course After Getting a Star: Ask" setting doesn't work right

### ISSUE THREAD

**Issue by sylveon-irl** [MorsGames/sm64plus#43]
With the "Ask" option enabled, when getting a star and choosing to leave the stage, it only works when it's the star of the mission the game perceives you as being on (i.e. the mission whose name shows up on the pause screen). Otherwise it just leaves you in the level, as if you chose the other option.

As an example, if you start a fresh file, get Star 6 from Bob-omb Battlefield, and choose to leave, you will stay in the level like nothing happened, but if you then go beat King Bob-omb and choose to leave again, then it'll work.

(I would really appreciate an "Always" option, as well... and my dream option would be "ask only when auto would unceremoniously whisk you out of the course so you never accidentally lose 100/red coin star progress, but also always automatically whisk you out of the course when you've gotten all 7 stars", but I understand that's a lot to ask for, lol.)

**Comment by MorsGames** [comment]
I rewrote the part of the code that handles all that stuff so in theory it should be all fixed now. Also, there has always been an "Always" option but it turns out that due to a bug on the Launcher it was inaccessible without editing the config files by hand. Whoops! That's now fixed as well.

But yeah, if the issue still persists please let me know.
